# Generated by Django 5.1.7 on 2025-03-25 20:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HOSRegulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "max_driving_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("max_duty_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "required_rest_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("cycle_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("cycle_days", models.IntegerField()),
                (
                    "break_required_after",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("break_duration", models.DecimalField(decimal_places=2, max_digits=5)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "HOS Regulation",
                "verbose_name_plural": "HOS Regulations",
            },
        ),
        migrations.CreateModel(
            name="LogDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.CharField(max_length=100)),
                ("start_location", models.CharField(max_length=255)),
                ("end_location", models.CharField(max_length=255)),
                ("total_miles", models.DecimalField(decimal_places=2, max_digits=10)),
                ("shipping_documents", models.CharField(max_length=255)),
                ("remarks", models.JSONField(default=list)),
                ("off_duty_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "sleeper_berth_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("driving_hours", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "on_duty_not_driving_hours",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Log Day",
                "verbose_name_plural": "Log Days",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="LogActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("offDuty", "Off Duty"),
                            ("sleeperBerth", "Sleeper Berth"),
                            ("driving", "Driving"),
                            ("onDutyNotDriving", "On Duty (Not Driving)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.CharField(max_length=10)),
                ("end_time", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "log_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="routes.logday",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Activity",
                "verbose_name_plural": "Log Activities",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_location", models.CharField(max_length=255)),
                ("end_location", models.CharField(max_length=255)),
                (
                    "total_distance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_duration", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Route",
                "verbose_name_plural": "Routes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="logday",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="routes.route",
            ),
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("pickup", "Pickup"),
                            ("dropoff", "Dropoff"),
                            ("rest", "Rest"),
                            ("fuel", "Fuel"),
                            ("overnight", "Overnight"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("arrival_time", models.CharField(max_length=100)),
                ("departure_time", models.CharField(max_length=100)),
                ("duration", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "mileage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="routes.route",
                    ),
                ),
            ],
            options={
                "verbose_name": "Route Stop",
                "verbose_name_plural": "Route Stops",
                "ordering": ["arrival_time"],
            },
        ),
    ]
